version: '3.4'

services:

  feedback:
    build: ./feedback
    ports:
      - "8000:8000"
    volumes:
      - ./sounds:/sounds
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - /home/pi/.config/pulse/cookie:/tmp/pulse/cookie:ro
    environment:
      - DISPLAY=
      - PULSE_COOKIE=/tmp/pulse/cookie
      - PULSE_SERVER=unix:/tmp/pulse/native
    restart: always

  recorder:
    build: ./recorder
    privileged: true
    volumes:
      - /dev/input:/dev/input
      - ./logs:/logs
    environment:
      - SAMPLE_NAME=${SAMPLE_NAME:-test}
      - RPI_HOST=${RPI_HOST}
    restart: always

  osc:
    build: ./osc
    ports:
      - "5000:5000/udp"
    volumes:
      - ./logs:/logs
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always

  jupyter:
    build: jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebook:/home/jovyan/notebook
      - ./logs:/logs
    restart: always
    command: start-notebook.sh --NotebookApp.token=''
